model_params: {
    growth_rate: 32,
    block_config: [6, 12, 24, 16],
    num_init_features: 64,
    bn_size: 4,
    drop_rate: 0,
    num_classes: 6,
    memory_efficient: False
}

dataset_params: {
    datapath: "/Users/isaiah/datasets/kaggle_mammograph/preprocessed/mammodata.h5",
    metadata_path: "/Users/isaiah/datasets/kaggle_mammograph/preprocessed/metadata.json",
    traintest_path: "/Users/isaiah/datasets/kaggle_mammograph/preprocessed/traintestsplit.json",
    augmentations: {"contrast_brightness"},
    labels: ["laterality", "view", "cancer", "implant", "density", "age"] 
}

optimizer_params: {
    lr: 3e-5    
}

train_params: {
    disable_cuda: False,
    epochs: 100,
    batch_size: 2,
    validation_size: 2,
    model_path: "/Users/isaiah/results/20220116/densenet_01.pth",
    report_path: "/Users/isaiah/results/20220117/densenet_rep_01.json",
    loss_weights: [0.1, 0.2, 0.45, 0.05, 0.1, 0.1]
}
